### ISSUE TITLE
Is it possible to add a note from a file?

### ISSUE THREAD

**Issue by shompoe** [jonhadfield/sn-cli#17]
Hi,

Using the windows version I can add a note, whereby the note text is part of the command line. But I haven't figured out how to create a note from a text file. Is this even possible?

**Comment by jonhadfield** [comment]
Hi, not currently. I'll see what's involved in implementing.

**Comment by shompoe** [comment]
Oh thanks,

I actually did some more digging around, looking at the get command for retrieving notes. Looks like the note comes to stdout only, and in json, and can't be redirected as stdout is used for 2FA prompt and other output too.

I wanted to use this to script backing up another program to xml and to store the backup (after splitting the file up) on SN. In the end this had to be a manual process using the official SN text file import tool.

I was also going to work out another scropt using the get command to retrieve the backup, before stitching them back together into one file. But looks like I wouldn't be able to do that at the moment.

--- 
Mark Desrousseaux



22 Sep 2020, 08:36 by notifications@github.com:

**Comment by jonhadfield** [comment]
So you want to be able to get a note to file and create a note from a file? It shouldn't be difficult to add an option, e.g. '-o output to file' on the get command. I did consider this before and got caught up in thinking where the title should go. For outputting to a file I guess the user could choose the filename and the file content would be the note content. For creating a note from file, I'll need to prompt for a title, and perhaps a list of tags.

**Comment by shompoe** [comment]
Hi,Thanks for you interest further developing this tool. Here are a few of my thoughts...

For scripting it would be better to avoid prompts, authentication with server might be an exception.

For creating a note from a file, if the title is not supplied as a parameter then it could take the filename as a default.

Likewise, when retrieving a note to a file, the file should contain the note text only. The name of the file could automatically follow the title of the note.

Regards tagging, i saw the app already has some tag functiinality but I didn't get that far. Could the tag/tags be a command line parameter when adding the note? And would it be possible also to retrieve multiple notes to files by specifying one of their tags?

Also, if a note already exists I guess I'd just get 2 notes with the same title right? What about an option to overwrite?

Regards
--- 
Mark Desrousseaux



22 Sep 2020, 11:43 by notifications@github.com:

**Comment by jonhadfield** [comment]
Option to add from file included in [release 0.2.4](https://github.com/jonhadfield/sn-cli/releases/tag/0.2.4).
