### ISSUE TITLE
004 protocol releasing soon

### ISSUE THREAD

**Issue by mobitar** [jonhadfield/sn-cli#18]
@jonhadfield just a heads up that the 004 protocol, featuring a new Sessions API and new cryptographic primitives will be going live sometime in the next 1-2 weeks. The encryption algorithms needed are XChaCha20-Poly1305 and Argon2id. Libsodium is the most popular library that supports these and the one we use.

https://github.com/standardnotes/snjs/blob/004/specification.md

Unless you enjoy a lot of pain and work, my recommendation is somehow finding a way to get the SNJS JavaScript library working in your Go environment.

Otherwise, you'll have to introduce new concepts like items keys and sessions. It's not impossible but seems like a lot of work.

**Comment by jonhadfield** [comment]
Thanks @mobitar. Early support now added.

**Comment by mobitar** [comment]
Very cool!
