### ISSUE TITLE
Email and Password rejected

### ISSUE THREAD

**Issue by GrouchyGaijin** [jonhadfield/sn-cli#20]
I can login to Standard Notes using my email and password and the Standard Notes app. The same email and password are rejected in sncli.

**Comment by jonhadfield** [comment]
Do you get any error message?

**Comment by GrouchyGaijin** [comment]
No, just that the email or password is incorrect.

`$sn tag testing
email: jfn@startmail.com
password: 
error: invalid email or password
`

**Comment by jonhadfield** [comment]
That's odd. Will have a look.

**Comment by GrouchyGaijin** [comment]
Anything else you need or that I can do to help fix the issue?

**Comment by jonhadfield** [comment]
Not yet, but thanks for the offer. I'm just trying to find time to try some different scenarios. 
I really need to add a warning on the front page too, as I've only just got the basic functionality working again after all the changes the SN team made to their API. 
Once I do fix this specific issue, please do ensure you have a backup!

**Comment by jonhadfield** [comment]
Hi @GrouchyGaijin, I've just published a new beta that _may_ fix this. If your account was created before Nov 2020, please upgrade to the latest encryption by performing a backup and then restore via the official SN web app. The reason is that I've dropped support for the legacy SN encryption 003 and now only support the newer, improved security, of the 004 version: https://docs.standardnotes.org/specification/encryption/

**Comment by GrouchyGaijin** [comment]
Hi Jon, 

I want to insure that I understand your instructions. My SN account was created well before November 2020 and when SN did update to the latest encryption scheme I updated as soon as I read about the update. 
What would you like me to do? Can I install this beta over the previous installation of your software? If not could you please tell me the command to uninstall the version that I initially installed? 

Thank you, 

GG (John) 

Sent from MailDroid

-----Original Message-----

**Comment by jonhadfield** [comment]
Hi, you can simply install it over the top of the existing binary.
Re: encryption, I'm not sure the upgrade actually upgrades all your existing items. I'm pretty sure I chose to upgrade but I still had a number of items encrypted with 003 afterwards.
To ensure everything is 004, I had to create a backup and then restore it.

**Comment by GrouchyGaijin** [comment]
Okay then I will back up and restore tomorrow when I get back to my computer. It just so happens that I had a totally unexpected gallbladder surgery yesterday and am almost set to leave the hospital today. 

Sent from MailDroid

-----Original Message-----

**Comment by jonhadfield** [comment]
I hope you have a speedy recovery.

**Comment by GrouchyGaijin** [comment]
It's all good - I went in, they took it out, gave me drugs for pain and are sending me home. Put another way, I am well enough to think about a text editor :-) 

Sent from MailDroid

-----Original Message-----

**Comment by GrouchyGaijin** [comment]
I just tried with the new beta. I backed up my files and restored them first, then I installed the new beta. Unfortunately I an getting the same invalid login or password error.

**Comment by jonhadfield** [comment]
There is a threshold on number of invalid logins set by SN themselves. Not sure how long before it expires.
I was thinking you may be on Windows, then noticed the `$` and lack of .EXE in your above comments. In any case, I've already noticed some Windows issues to investigate.
Could you try this test account please?
$ export SN_EMAIL=sn-cli-202104101323@lessknown.co.uk
$ export SN_PASSWORD=sn-cli-202104101323
$ sn stats
Also, could you run
$ sn --version
Just to make sure you're running the latest binary, and it's not an old version in your path.
If the above works, could you try exporting your email and password and try? If that works, it might be the way in which the credentials are being read at the console.

**Comment by GrouchyGaijin** [comment]
When I try sn stats with the email:
***@***.****
and password:
*sn-cli-202104101323*

I get the invalid  email or password version error.

$sn stats
email: ***@***.***
password:
error: invalid email or password

$sn --version
sn version [0.1.0-beta4-76361b0] 2020/07/04:15:53:57 UTC



/John

**Comment by jonhadfield** [comment]
Can you try this release instead?
https://github.com/jonhadfield/sn-cli/releases/tag/0.1.0-beta5
I made a bunch of changes, including authentication works.

**Comment by GrouchyGaijin** [comment]
Getting closer!
It initialized before it crashed this time.
I used my actual credentials and not the test credentials you posted earlier.

`$sn stats
email: jfn@startmail.com
password: 
initialising ⠙ panic: validation failed for "SF|Extension" due to missing ItemsKeyID: "8e17bd17-3356-4659-a1e4-d78d6b1b509b"

goroutine 1 [running]:
github.com/jonhadfield/gosn-v2.Sync(0xc0003e1b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210502115433-07e0fea798a2/sync.go:124 +0xc68
github.com/jonhadfield/gosn-v2/cache.Sync(0xc00026e530, 0x0, 0x0, 0xbb9220, 0xc0000b1200)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210502115433-07e0fea798a2/cache/cache.go:358 +0xcc6
github.com/jonhadfield/sn-cli.sync(...)
	/home/circleci/project/sync.go:38
github.com/jonhadfield/sn-cli.Sync(0xc00026e530, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/sync.go:22 +0x1cc
github.com/jonhadfield/sn-cli.(*StatsConfig).Run(0xc00026e530, 0x0, 0x0)
	/home/circleci/project/stats.go:26 +0x55
main.startCLI.func28(0xc0000f0c60, 0x0, 0xc000134f40)
	/home/circleci/project/cmd/sncli/main.go:906 +0x278
github.com/urfave/cli.HandleAction(0xa03e00, 0xc000134b80, 0xc0000f0c60, 0xc0000f0c60, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xbe
github.com/urfave/cli.Command.Run(0xad09f5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xadb511, 0xf, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x528
github.com/urfave/cli.(*App).Run(0xc0001241c0, 0xc0000be020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x731
main.startCLI(0xc0000be020, 0x2, 0x2, 0xc000190000, 0xc000134ae0, 0xc00016bf20, 0x43d347, 0xf87a80)
	/home/circleci/project/cmd/sncli/main.go:1014 +0x37cd
main.main()
	/home/circleci/project/cmd/sncli/main.go:45 +0x57
`

**Comment by jonhadfield** [comment]
That's authentication sorted!
You've got exactly the same issue I'm debugging right now. It's odd, as all items should have an Items Key associated with them, but Extensions seem to be an exception. I'll have a dig through the SN code and maybe ping their main developer in case it's a bug on their side.
Thanks for your patience.

**Comment by GrouchyGaijin** [comment]
Actually, thank you! I am not a programmer, just a lowly end user. Basically your project is something I have wanted since I began using SN. I am looking forward to this bug being squashed :-)

**Comment by jonhadfield** [comment]
I've raised an issue with the SN team to have a look at: https://github.com/standardnotes/syncing-server/issues/198
It only appears to be an issue with extension items, so I'll look to suppress those for now.

**Comment by jonhadfield** [comment]
Sorry for the delay.
The SN team told me that certain types of items are not encrypted. These items don't contain any of your data though, so it's not a security issue. The bug is that my code is expecting all items to be encrypted, so when it discovered these special types, it threw the error relating to 'SF|Extension' that you saw.
Beta 6 resolves that issue: https://github.com/jonhadfield/sn-cli/releases/tag/0.1.0-beta6

**Comment by GrouchyGaijin** [comment]
Hey Hey - looking good!
`$sn add tag --title valus TESTING
email: xxx@xxx.com
password: 
Added: valus
`

**Comment by GrouchyGaijin** [comment]
Now I just need to play with it some to figure out how best to use your program.

**Comment by jonhadfield** [comment]
Great. Just shout if you have any other issues.
