### ISSUE TITLE
Stack trace on `stats`

### ISSUE THREAD

**Issue by issmirnov** [jonhadfield/sn-cli#21]
I installed the latest release, and when running `sn --use-session stats` I got a stack trace:

```
sn --use-session stats       
initialising ⠴ panic: validation failed for "Note" due to missing ItemsKeyID: "89645322-a4f6-4ad1-a0b6-135496ecf746"

goroutine 1 [running]:
github.com/jonhadfield/gosn-v2.Sync(0xc0001b43c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210506195140-d4f22f23e149/sync.go:124 +0xc85
github.com/jonhadfield/gosn-v2/cache.Sync(0xc000140538, 0x0, 0x0, 0xbb9180, 0xc000073210)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210506195140-d4f22f23e149/cache/cache.go:357 +0xcec
github.com/jonhadfield/sn-cli.sync(...)
	/home/circleci/project/sync.go:38
github.com/jonhadfield/sn-cli.Sync(0xc000140538, 0x0, 0x9f4201, 0x1, 0xc0001ea0e0, 0xc00013ff30)
	/home/circleci/project/sync.go:22 +0x1c4
github.com/jonhadfield/sn-cli.(*StatsConfig).Run(0xc000140538, 0x0, 0x0)
	/home/circleci/project/stats.go:25 +0x4f
main.startCLI.func28(0xc0000d0840, 0x0, 0xc00010cf50)
	/home/circleci/project/cmd/sncli/main.go:901 +0x27c
github.com/urfave/cli.HandleAction(0xa03e00, 0xc00010cb90, 0xc0000d0840, 0xc0000d0840, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xbe
github.com/urfave/cli.Command.Run(0xad09b7, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xadb4d3, 0xf, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x528
github.com/urfave/cli.(*App).Run(0xc0000fe1c0, 0xc000020180, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x731
main.startCLI(0xc000020180, 0x3, 0x3, 0xc000164000, 0xc00010caf0, 0xc000141f20, 0x43d347, 0xf88a80)
	/home/circleci/project/cmd/sncli/main.go:1009 +0x37cd
main.main()
	/home/circleci/project/cmd/sncli/main.go:45 +0x57

```

SN version: `sn version [0.1.0-beta6-e7e8342] 2021/05/06:20:37:35 UTC`

Host OS: Ubuntu 20.04, running on AMD x64

**Comment by jonhadfield** [comment]
Hi @issmirnov. Thanks for flagging this.
Standard Notes changed the way items (notes, tags, etc.) are encrypted last November. With the new version (004) they added an extra layer of encryption that requires every item has an 'ItemsKeyId'.
Whilst the official apps support the legacy version (003), as well as the latest, I dropped support for the old version to keep the codebase simpler and easier to maintain. The error suggests you still have some items encrypted using legacy.

If you do an export and then import using the official app, that will re-encrypt all your items to the new encryption. Please could you try that and then see if you still get the error?

In the meantime, I'll work on making the error more informative.

**Comment by issmirnov** [comment]
Thanks! I think I upgraded to v4, since I use strict sign in. I'll try to delete all data and re-upload, then update here.

**Comment by issmirnov** [comment]
Perfect, it works now. Thank you! I see the updated error message as well.
