### ISSUE TITLE
sn get note with jq

### ISSUE THREAD

**Issue by sigmonsays** [jonhadfield/sn-cli#22]
i'd expect piping to stdout to work correctly with jq
```

u@s1:~$ sn get note | jq .
parse error: Invalid numeric literal at line 1, column 3
```

**Comment by jonhadfield** [comment]
Hi @sigmonsays. The items are output, one after the other, rather than in a valid json array. I think I've worked out a fix but will need a bit of testing.

**Comment by jonhadfield** [comment]
I've just published a [new release](https://github.com/jonhadfield/sn-cli/releases/tag/0.1.0-beta7) that outputs valid json. Please try again and let me know.

**Comment by sigmonsays** [comment]
nice work!
