### ISSUE TITLE
Email and Password still rejected

### ISSUE THREAD

**Issue by Robert-Ernst** [jonhadfield/sn-cli#23]
Hello,

I have read https://github.com/jonhadfield/sn-cli/issues/20 and I don't see any other way to debug.
I'm on `OSX Big Sur` and having this version of sn-cli installed: 
`sn version [0.1.0-beta7-49558fd] 2021/07/19:17:46:18 UTC`

When I try to use any command like 
`sn --debug stats`
and entering my email and password I will simply get a:
`err: invalid email or password`

**Comment by Robert-Ernst** [comment]
I updated the version:
sn version [0.1.1-0b29966] 2021/10/24:18:03:45 UTC

```2021/11/08 21:01:27 gosn-v2 | attempting cli sign-in with email: 'foobar' 18 char password and server 'https://sync.standardnotes.org'
2021/11/08 21:01:30 gosn-v2 | requesting session token api: 20200115 encPassword len: 64 email: foobar
2021/11/08 21:01:30 gosn-v2 | sign-in url: https://sync.standardnotes.org/auth/sign_in
2021/11/08 21:01:31 gosn-v2 | requestToken | request took: 1.461021441s
2021/11/08 21:01:31 gosn-v2 | requestToken | response read took 49.41µs
2021/11/08 21:01:31 gosn-v2 | CliSignIn failed with: invalid email or password
err: invalid email or password
```

I also changed the password as advised and can confirm that they are correct since I'm logged in online with those credentials.

Any suggestions for further debugging?

**Comment by jonhadfield** [comment]
I see it's still using the legacy domain (sync.standardnotes.org) in your output and I've found the issue in my code that results in that being the default.  
Please could you try the same command again, but first enter:
`export SN_SERVER=https://api.standardnotes.com`
and then:
`sn --debug stats`
It should then have this in the output when you try to sign-in:
`2021/11/08 20:29:35 gosn-v2 | sign-in url: https://api.standardnotes.com/auth/sign_in`
If that still fails, then please could you try and rule out some basics, e.g. typing your password manually (if you were copying and pasting before), confirm your email address is all lower case with no special characters, etc.? When you log in to the SN website or desktop app, can you choose the 'Account' option in the bottom left and then compare how your email is displayed and the API url beneath? Maybe try different terminal, e.g. `iTerm2` and the built in `Terminal`.
I'll fix the API URL and add some more tests to the code in the meantime.

**Comment by Robert-Ernst** [comment]
```export SN_SERVER=https://api.standardnotes.com```
```sn --debug stats``` 
```email: foobar```
```password: foobar```

```2021/11/09 10:14:52 gosn-v2 | attempting cli sign-in with email: 'foobar' 18 char password and server 'https://api.standardnotes.com'
2021/11/09 10:14:53 gosn-v2 | requesting session token api: 20200115 encPassword len: 64 email: foobar
2021/11/09 10:14:53 gosn-v2 | sign-in url: https://api.standardnotes.com/auth/sign_in
2021/11/09 10:14:55 gosn-v2 | requestToken | request took: 1.140637077s
2021/11/09 10:14:55 gosn-v2 | requestToken | response read took 37.164µs
2021/11/09 10:14:55 gosn-v2 | CliSignIn failed with: invalid email or password
err: invalid email or password
```

**Comment by Robert-Ernst** [comment]
I also entered password and email manually as requested.
My email contains a plus operator - maybe that makes problems?

Furthermore I logged into the web client again at https://app.standardnotes.com/
and there it works fine. Also my email is shown (including the + operator) as it should.

I furthermore tried another terminal. No change.

**Comment by jonhadfield** [comment]
I just created a test account with a plus sign in the email address and I can recreate the issue!
I know it's valid email syntax as I use them myself sometimes. I just haven't done with SN before.

I'll have a play and try and find out what's going wrong.

**Comment by Robert-Ernst** [comment]
Good debugging skills! I know it's not easy to trying to catch every possible cause.
Glad that you had the right clue 👍

**Comment by Robert-Ernst** [comment]
How is the status? @jonhadfield

**Comment by jonhadfield** [comment]
Sorry for the delay. I fixed the issue (encoding the email address), but also had to update to the new API domain that SN have set. This resulted in disappearing down the rabbit-hole of numerous other code changes and tests to fit with the new API. I'll _try_ and get a release out this evening.

**Comment by Robert-Ernst** [comment]
My condolences. Could have be worse!, you got have gotten down the path of learning vim or emacs!

**Comment by jonhadfield** [comment]
I put a new release out yesterday that should fix this issue. Please let me know how you get on.

**Comment by Robert-Ernst** [comment]
This problem seems solved. It is able to login.
It clearly fetches personal data but it still aborts with an error, followed up here:

https://github.com/jonhadfield/sn-cli/issues/24

**Comment by jonhadfield** [comment]
Thanks for the feedback. I'll close this and continue with the other issue.
