### ISSUE TITLE
panic: validation failed for "SN|Component" due to missing ItemsKeyID

### ISSUE THREAD

**Issue by Robert-Ernst** [jonhadfield/sn-cli#24]
Coming from https://github.com/jonhadfield/sn-cli/issues/23 there is a follow up error which is not related to the original login problem.

`sn version`
   [0.1.2-024380e] 2021/11/17:21:17:34 UTC
   
`sn --debug stats`
> [...] (Successful processing, following are the last lines of output)

> 2021/11/21 06:43:16 gosn-v2 | Sync | took 7.844894996s to get all items
2021/11/21 06:43:16 gosn-v2 | Sync | post processing took 1.380252ms
2021/11/21 06:43:16 gosn-v2 | Sync | sync token: foobar
2021/11/21 06:43:16 gosn-v2 | Sync | duration 7.846323335s
panic: validation failed for "SN|Component" due to missing ItemsKeyID: "foobar"

> goroutine 1 [running]:
github.com/jonhadfield/gosn-v2.Sync(0xc00009e2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20211117204829-e02435d4d0db/sync.go:118 +0xca4
github.com/jonhadfield/gosn-v2/cache.Sync(0xc000142538, 0xc0000a7d00, 0x0, 0x1771960, 0xc0000812b0)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20211117204829-e02435d4d0db/cache/cache.go:362 +0xd1c
github.com/jonhadfield/sn-cli.sync(...)
	/home/circleci/project/sync.go:40
github.com/jonhadfield/sn-cli.Sync(0xc000142538, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/project/sync.go:32 +0x38d
github.com/jonhadfield/sn-cli.(*StatsConfig).Run(0xc000142538, 0x0, 0x0)
	/home/circleci/project/stats.go:25 +0x4f
main.startCLI.func28(0xc00009f080, 0x0, 0xc00010d050)
	/home/circleci/project/cmd/sncli/main.go:900 +0x27c
github.com/urfave/cli.HandleAction(0x15cd600, 0xc00010cc90, 0xc00009f080, 0xc00009f080, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xbe
github.com/urfave/cli.Command.Run(0x16920c1, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1699211, 0xf, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x528
github.com/urfave/cli.(*App).Run(0xc0000fc1c0, 0xc000082180, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x731
main.startCLI(0xc000082180, 0x3, 0x3, 0xc000150000, 0xc00010cba0, 0xc000143f20, 0x103adc7, 0x1b17b60)
	/home/circleci/project/cmd/sncli/main.go:1008 +0x37cd
main.main()
	/home/circleci/project/cmd/sncli/main.go:45 +0x57

Same for this command:

`sn get note`
email: 
password:

> syncing ⠹ panic: validation failed for "SN|Component" due to missing ItemsKeyID: "foobar"

> goroutine 1 [running]:
github.com/jonhadfield/gosn-v2.Sync(0xc000020580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20211117204829-e02435d4d0db/sync.go:118 +0xca4
github.com/jonhadfield/gosn-v2/cache.Sync(0xc00000dc00, 0x0, 0x0, 0x1771960, 0xc00005f2c0)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20211117204829-e02435d4d0db/cache/cache.go:362 +0xd1c
github.com/jonhadfield/sn-cli.sync(...)
	/home/circleci/project/sync.go:40
github.com/jonhadfield/sn-cli.Sync(0xc00000dc00, 0x0, 0xc000022001, 0xc000022fe0, 0xc0000230a0, 0x0)
	/home/circleci/project/sync.go:26 +0x200
github.com/jonhadfield/sn-cli.(*GetNoteConfig).Run(0xc0001273b8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/note.go:118 +0x6c
main.processGetNotes(0xc000020f20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/cmd/sncli/note.go:378 +0x78e
main.startCLI.func23(0xc000020f20, 0x0, 0xc0000fa1e0)
	/home/circleci/project/cmd/sncli/main.go:703 +0xe4
github.com/urfave/cli.HandleAction(0x15cd600, 0xc00000d360, 0xc000020f20, 0xc000020f20, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xbe
github.com/urfave/cli.Command.Run(0x16913bd, 0x4, 0x0, 0x0, 0xc0000f4ce0, 0x1, 0x1, 0x1695998, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x528
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000e6380, 0xc000020c60, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x882
github.com/urfave/cli.Command.startApp(0x16909ff, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x169598f, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x845
github.com/urfave/cli.Command.Run(0x16909ff, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x169598f, 0x9, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x99c
github.com/urfave/cli.(*App).Run(0xc0000e61c0, 0xc00001e1b0, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x731
main.startCLI(0xc00001e1b0, 0x3, 0x3, 0xc000136000, 0xc0000f4bb0, 0xc000129f20, 0x103adc7, 0x1b17b60)
	/home/circleci/project/cmd/sncli/main.go:1008 +0x37cd
main.main()
	/home/circleci/project/cmd/sncli/main.go:45 +0x57

**Comment by jonhadfield** [comment]
#### Background
Each item (a note, a tag, a component, etc.) is encrypted by its own individual key, and those keys are encrypted by one or more Items Keys. Every item in every account created since Nov 2020 should be encrypted in this way, and should have a corresponding Items Key. If your account is older, changing your password forces every every item to be re-encrypted using this scheme, hence the suggestion on #23.

I'm really confused as to how this can happen on an account where the password has been changed since Nov 2020. The reason you don't see any useful debug output is because this is a situation I didn't expect (hence the 'panic'). I'll see if there's some additional error handling I can add, and some more debug output that might be useful.

**Comment by jonhadfield** [comment]
I've discovered that it's possible for a user to have invalid items in the SN database. Whilst the official app will ignore them, my app would panic as it assumes it should never happen.
I've just pushed a new release that will ignore these invalid items also: https://github.com/jonhadfield/sn-cli/releases/tag/0.1.5

**Comment by Robert-Ernst** [comment]
`sn --version`
sn version [0.1.5-9398d8a] 2021/11/22:13:18:03 UTC

`sn get note`
email: 
password:

> err: your account contains items encrypted with an earlier version of Standard Notes
to upgrade your encryption, perform a backup and restore via the official app

**Comment by jonhadfield** [comment]
Every item (tag, note, etc.) has an attribute that specifies the version of encryption used; The current version is 004.
IIRC, a password change re-encrypts everything, but I'm wondering if somehow the version field is empty, i.e. there are yet more invalid items.
I'll improve the debug output to show the content of the version field as that would help isolate the issue.

**Comment by jonhadfield** [comment]
I've just pushed a new release that will hopefully highlight where the issue is. If it really does turn out to be 003 in the version field, I suspect a backup and restore is the only way to remedy. Whilst I could ignore 003, it would mean valid, yet old, items may not be available.

**Comment by Robert-Ernst** [comment]
> err: your account contains an item (uuid: "foobar" type: "SN|Component" encryption version: "003") encrypted with an earlier version of Standard Notes
> to upgrade your encryption, perform a backup and restore via the official app

**Comment by jonhadfield** [comment]
That means your account is from before Nov 2020 and only a backup and restore _should_ ensure you only have version 004 afterwards.

**Comment by Robert-Ernst** [comment]
Yeah, I gave up.
I exported. Created a new account and now it's working
