### ISSUE TITLE
Issue with encrypted/decrypted exports?

### ISSUE THREAD

**Issue by ashutoshsaboo** [jonhadfield/sn-cli#27]
Hi @jonhadfield , thanks for building this tool! I tried out the encrypted export via sn-cli, it exports into a `.gob` file extension. This does not seem to be similar to the txt format with encrypted jsons that SN officially exports, which is why their official decrypt tool also doesn't work with this file - https://github.com/standardnotes/decrypt. How can I open/decrypt this file? Not sure if it's any kind of limitation, but Is it possible to export in the same json list format that SN also exports in to maintain consistency and re-use the decrypt tool vended out by SN? 

I also tried to do a decrypted export, but seems like the nested CLI options are broken? `sn export --help` clearly shows 2 options as available - `--encrypted` and `--output`. However on trying to use them I get the below error (i'm on macOS and using the `sn-cli_Darwin_amd64.zip` version linked here - https://github.com/jonhadfield/sn-cli/releases -- If this is the wrong version that i'm using please let me know which one I should be using). Can this bug be fixed if possible @jonhadfield ? 

See stack trace below:
```
(base) macos@88665a14b29c ~ % sn export --encrypted false --output ./test/
Incorrect Usage: flag provided but not defined: -encrypted

NAME:
   - export - export data

USAGE:
   - export [command options] [arguments...]

OPTIONS:
   --encrypted (default: true)                  encrypt the exported data
   --output (default: current directory) value  output path

err: flag provided but not defined: -encrypted
```

**Comment by jonhadfield** [comment]
Hi @ashutoshsaboo, thanks for the feedback.
As I wrote this in the go programming language, for simplicity, I decided to use a standard library package called [gob](https://pkg.go.dev/encoding/gob). The benefit is that all of the data downloaded from standardnotes will be packaged into a single file. The downside is that it can only be read using this app. If you run `strings your-export-file.gob | less` you can see the raw data is all there, with a little extra data that means the app knows how to restore it. I'll check how complex it would be to produce the same format as SN does.

There's definitely a bug in how the --encrypted flag works currently that I'll take a look at asap.

**Comment by ashutoshsaboo** [comment]
@jonhadfield But the SN encrypted export (their format) is also a single Json file only. It consists of a standard json array including all your encrypted tags/notes/extensions etc. That ways, this single file can be decrypted easily using the offline file picker in this html (officially vended out by SN team) - https://github.com/standardnotes/decrypt . I'll admit i haven't used a lot of Go, but I thought json was largely an interoperable format with good support in most languages including Go? Maybe if you can try doing the export in that same format that'd be pretty awesome! :)

**Comment by ashutoshsaboo** [comment]
Hi @jonhadfield any update on this? For interoperability, I really would like to have this CLI export in the same format as what SN vends out. From an initial look, It looks like you already have all the data that SN also vends out in it's export so looks like just a formatting thing, which should be a minor fix? I'd have submitted a PR, but unfortunately i'm new to Go :( , so would really appreciate any help for this!

**Comment by jonhadfield** [comment]
Hi @ashutoshsaboo, I've just pushed [a new beta release](https://github.com/jonhadfield/sn-cli/releases/tag/0.2.0-beta1) with a number of significant changes to the code. It includes a change to the way exports and imports are done, switching to JSON only, and should be compatible with the official SN applications.   
Please make sure you have a backup via the official app, just in case there are any bugs.

**Comment by ashutoshsaboo** [comment]
Hey @jonhadfield , thanks first of all - appreciate it! I just tried, the json seems to be valid, but the decryption via SN's decrypt tool (https://github.com/standardnotes/decrypt) doesn't seem to work - it always shows incorrect password for some reason. I double-checked the password I entered was correct. Possibly did you try it earlier, if it worked for you?

**Comment by jonhadfield** [comment]
I've discovered the offline decryption tool expects something called the 'Items Key's to be present also. That _should_ hopefully resolve this issue. I'll see if I can get a release out tonight/tomorrow.

**Comment by ashutoshsaboo** [comment]
@jonhadfield sounds good, let me know whenever you are able to make the release -- i'll be happy to test it out once you are able to get the changes out!

**Comment by jonhadfield** [comment]
I've had to make a lot of changes and add a number of tests to get this working as I wasn't previously managing ItemsKeys (the ones that encrypt the keys that encrypt your content) in full. This uncovered a bunch of other dependencies and bugs that I've been chasing and fixing over a number of days.   

I _think_ I'm nearly done and will shout as soon as I've managed to get the release out.

**Comment by jonhadfield** [comment]
Sorry for the delay. There's very little documentation on how to manage conflicts (importing when a newer, same age, or older item already exists) and all of the steps to export and import in a way compatible with SN. Anyhow, I've put out a release for to try https://github.com/jonhadfield/sn-cli/releases/tag/0.2.0-beta4.  
It passes all the tests I've written, and the [decrypt](https://github.com/standardnotes/decrypt) tool now seems happy with the exports. I'm still a little concerned with the import functionality though (hence the warning you'll now see when you run `sn import`), and have a few more things to check before I'm happy.

**Comment by jonhadfield** [comment]
Closing, but let me know if you have any issues. I'm close to a general release, but please try out latest beta in the meantime (after taking a backup using the official SN web app).
