### ISSUE TITLE
sn add note --replace not working

### ISSUE THREAD

**Issue by Robert-Ernst** [jonhadfield/sn-cli#28]
Working on Ubuntu
sn version [0.2.0-beta1-e7cb9c0] 2021-12-29T19:59:52Z

`sn add note --replace --title mytest --text whatever`
creates a new note instead of replacing one of the same name.
Please check and leave feedback

Probably related to https://github.com/jonhadfield/sn-cli/issues/3

**Comment by jonhadfield** [comment]
This should be fixed in: https://github.com/jonhadfield/sn-cli/releases/tag/0.2.0.

**Comment by jonhadfield** [comment]
Closing, but please shout if not working.
