### ISSUE TITLE
sn add note --text doesn't support multiline input

### ISSUE THREAD

**Issue by Robert-Ernst** [jonhadfield/sn-cli#29]
Working on Ubuntu
sn version [0.2.0-beta1-e7cb9c0] 2021-12-29T19:59:52Z

I tried several delimiters to create multiline notes and haven't succeeded.
The documentation doesn't provide any information about it.
I tried env_variables, pipes and xargs.

Related to https://github.com/jonhadfield/sn-cli/issues/17
This would be an alternative solution which I would love to see implemented aswell

**Comment by jonhadfield** [comment]
You should be able to simply open double quotes and then hit return to enter line breaks as long as you finish with double quotes again, e.g.
```
sn add note --title hello --text "This is some
text that will go across
multiple lines"
```

**Comment by jonhadfield** [comment]
Closing, but please shout if you still have the issue.
