### ISSUE TITLE
Add text to an existing note

### ISSUE THREAD

**Issue by Soleone** [jonhadfield/sn-cli#3]
I might be missing something, but I can't seem to find out how to add new text to an existing note. The `add` command just always seems to create a new note (and I end up with duplicate notes with the same title).

Is this not supported yet? Is it hard to support? I would have imagined that is a fairly common use case. For example I have a "todo" note and every day I add new content there.

**Comment by jonhadfield** [comment]
The use-case isn't currently supported. It's definitely something I'd like to add in future but it requires a significant amount work to ensure: 1) the item is securely stored whilst being edited, 2) there are no sync conflicts when the edited item is pushed back to the server.

If you want to be able to edit content for multiple notes, you might want to consider mounting SN as a filesystem: https://github.com/tannercollin/standardnotes-fs.

**Comment by Robert-Ernst** [comment]
https://github.com/tannercollin/standardnotes-fs
was archived and doesn't help anymore
