### ISSUE TITLE
sn sessions --add - err: secret not found in keyring

### ISSUE THREAD

**Issue by passuf** [jonhadfield/sn-cli#30]
First of all, thanks a lot for implementing this CLI, I have many use cases where this could get really useful.

### Setup
- Ubuntu 21.10 with `gnome-keyring` and `dbus-x11` installed.
- sn-cli version `[0.2.0-beta1-e7cb9c0] 2021-12-29T19:59:52Z`
- StandardNotes with all notes migrated to 004 and 2FA setup.

Token authentication (e.g. when running `./sn stats`) works perfectly fine.

### Problem
I tried to authenticate using sessions, but when trying to create a new one I get the following error:

```
passuf@localhost> ./sn session --add            
err: secret not found in keyring
```

**Comment by jonhadfield** [comment]
Sorry for the delay. Please could you try with the latest beta? I just tested on Ubuntu 20.04 and didn't have any issues.

**Comment by passuf** [comment]
Just tried it with version `0.2.2` and now it works like a charm! Thank you very much!
