### ISSUE TITLE
Cant run any command, payload too large

### ISSUE THREAD

**Issue by baalajimaestro** [jonhadfield/sn-cli#53]
[log.txt](https://github.com/jonhadfield/sn-cli/files/13716908/log.txt)

**Comment by baalajimaestro** [comment]
Seems to be fixed by 9a95e3ad88e5fdc470110cccc891c24221a91190

**Comment by jonhadfield** [comment]
Thanks for the update. I've just pushed 0.3.1 that also includes some additional debug data and an extra retry (with smaller number of items per request) in case of failure.
